---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family=="Debian"

    - name: Install nginx on RedHat family
      yum:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"

    - name: Star httpd daemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"

    - name: Create user Serge
      user:
        name: Serge
        comment: Serge Smith
        shell: /bin/bash

    - name: Create group cloudteam
      group:
        name: cloudteam
        state: present  # Assuming you want to create this group

    - name: Create index file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Create directory /tmp/os
      file:
        path: /tmp/os
        state: directory

    - name: Copy content to index
      copy:
        dest: /var/www/html/index.html
        content: "<h1>This is created using ansible</h1>"