---
- hosts: ws
  become: true
  become_user: root
  ignore_errors: true
  tasks:
    - name: Delete old artifacts
      file:
        path: /opt/qa/spg/*.jar
        state: absent

    - name: Get the PID
      shell: lsof -t -i :8081
      register: pid_output
      tags: 
        - a
    - name: print pid_output
      debug:
        var: pid_output
      tags:
        - b
    
    - name: Kill running app
      shell: kill -9 "{{ pid_output.stdout }}"
      when: pid_output.stdout != ''

    - name: Download new artifacts
      get_url:
        url: http://52.3.250.12:8081/artifactory/geolocation/geo/bio_19.jar
        dest: /opt/qa/spg
        url_username: admin
        url_password:  password

    - name: Run the app
      shell: nohup java -jar /opt/qa/spg/*.jar > /opt/qa/spg.log 2>&1 &